### ISSUE TITLE
Button LEDs sticking on

### ISSUE THREAD

**Issue by Gadgetoid** [pimoroni/touch-phat#3]
Under some circumstances the button LEDs seem to stick in the on state. Since the library depends upon receiving and handling the release event to turn LEDs off (in auto mode) it seems there's something awry with event handling or detection.

This could potentially be solved by changing the LEDs to pulse mode, so that the hardware itself handles turning them on for a brief period, and then automatically sets them off.

**Comment by ConorMatthews** [comment]
I'm also having this problem 👎

**Comment by Gadgetoid** [comment]
Can you replicate it at will? Some steps may help in tracking down why it happens.

I might just add a Python timer to reset the LEDs to off after a short while if a release event is missed.

**Comment by Gadgetoid** [comment]
This is not actually a bug in Touch pHAT but, in fact, a bug in Cap1xxx.

It's also the consequence of doing *too much* in button handlers, all of which are run in the same, single polling thread used for Cap1xxx.

Generally the `on_press` and `on_release` handlers should follow some simple rules:

* Do as little as possible
* Never use time.sleep or any other code to cause delays
* Exit quickly

Since only one `on_press` or `on_release` handler can be run at any one time, the library relies upon them to be quick and efficient. If you do too much, then the unfortunate side-effect is that the release events for button presses happen right before the last cycle of interactions and are then cleared.

This is caused by this code:

```python
    def _handle_alert(self, pin=-1):
        inputs = self.get_input_status()
        for x in range(self.number_of_inputs):
            self._trigger_handler(x, inputs[x])
        self.clear_interrupt()
```

https://github.com/pimoroni/cap1xxx/blob/be4f15526abc4cf895a4dd3c07005f9c49c94b73/library/cap1xxx.py#L448-L452

Briefly it:

1. Gets the status of all buttons on Touch pHAT
2. Runs through each input and calls the appropriate handlers
3. Clears the interrupt flag 

This means that any delay in step 2 can cause the interrupt flag to be cleared *after* new and unhandled interrupts have been generated. In the case of a single quick press and release, the release event is simply lost- clear accidentally by this flag.

For example in this case, the event warning of the release at `a` would be cleared before it's ever handled:

1. Get status
2. Run through each input
    a. Button is released
3. Interrupt is cleared

This should really be:

1. Get status
2. Clear flag
3. Handle inputs

This change should fix "stuck" buttons, but it wont fix problems caused by long-running interrupts.

In the time it takes between step 2. and finishing step 3. there could have been any number of press/release events generated and missed. So always be careful!

A good pattern is:

```python
import touchphat

@touchphat.on_touch(['Back'])
def handle_touch(event):
    global back_pressed
    back_pressed = True

while True:
    if back_pressed:
        # Do something
        back_pressed = False
```

This still doesn't catch rapid presses of a button, but you can at least derive some way of counting presses and processing them that fits within this paradigm.
