### ISSUE TITLE
Back button not registering tap

### ISSUE THREAD

**Issue by sandyjmacdonald** [pimoroni/touch-phat#6]
The Back button doesn't register a tap in Raspbian Buster on the Pi 4.

**Comment by Gadgetoid** [comment]
Make sure you plug on the Touch pHAT while holding it from the edges- it might well be that a button was "held down" during power-on calibration.

I believe there's a way to mitigate this when the library starts by forcing a recalibration- we did this for touch:bit IIRC, so I'll mark this an enhancement and keep it open.
