### ISSUE TITLE
Primoroni Touch Phat, Hifiberry Mini Amp, On Off Shim

### ISSUE THREAD

**Issue by StL2412** [pimoroni/touch-phat#7]
Hello guys, i need help with my project. I dont wanna use hardware buttons for my phoniebox. Thats the reason i choosed the primorino touch phat buttons. The Problem is, that the touch phat and the Hifiberry Mini Amp uses the same gpios. When i dont use the touch phat everythings works fine. Iam using the Raspian Stretch One Line install without Spotify. Can someone help me with a soldering plan or any other idea to get all the buttons and the amp works?

**Comment by Gadgetoid** [comment]
Touch pHAT uses *just* i2c, so as long as it doesn't have an address conflict with whatever i2c is used on the Amp I don't see any reason why it shouldn't work.

With just the Amp installed, what do you see if you run:

```
sudo i2cdetect -y 1
```

Same thing with the Amp and the Touch pHAT.

**Comment by StL2412** [comment]
when i do sudo i2cdetect -y 1 it says
     0  1  2  3  4  5  6  7  8  9  a  b  c  d  e  f
00:          -- -- -- -- -- -- -- -- -- -- -- -- -- 
10: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
20: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
30: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
40: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
50: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
60: -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- 
70: -- -- -- -- -- -- -- --     

but idont know what it means. The rpi says Warning, could not find Analog or Touch...
Please check your i2c settings!

the touch phat pinout says that it uses i2c Pin 3 & 5. This are the same one like the hifiberry miniamp uses. Can i change one of these to pin 27 & 28?

**Comment by Gadgetoid** [comment]
Two devices should be able to share the same i2c pins (it's an addressible bus, a bit like a tiny local network), but you appear to be seeing nothing at all on the i2c bus.

When you ran `sudo i2cdetect -y 1` what devices did you have connected?

The table you're seeing is just a list of the available addresses- every connected i2c device should have an address and show up in that table.

**Comment by StL2412** [comment]
I connected the Pimoroni TouchPhat and the Hifiberry Miniamp. The Amp is working now. But the the TouchPhat is still not.

**Comment by Gadgetoid** [comment]
As near as I can tell there are no pin conflicts between Hifiberry Mini Amp and Touch pHAT.

Touch pHAT pins - https://pinout.xyz/pinout/touch_phat

The Mini Amp uses physical pins 12, 35, 38 and 40 (found here: https://www.hifiberry.com/docs/hardware/gpio-usage-of-hifiberry-boards/)

How are you connecting both of these devices to your Pi?

**Comment by StL2412** [comment]
Thanks for the help. I bought another pi b+ (It’s already the third) and it works fine now. I guess the two others was broken.
