### ISSUE TITLE
Printing causes button to toggle

### ISSUE THREAD

**Issue by MegaAdragon** [pimoroni/touch-phat#8]
I'm trying to implement a simple button handling mechanism that distinguishes between short and long button presses. However this only works very unstable, because as soon as I start to print something in my script, the button state can no longer be handled reliably. The `on_release` and `on_press` events are triggered multiple times and the LED of the pressed buttons and flashing rapidly. 
Somehow I'm not able to do a reliable long press on one of the buttons without triggering this behaviour... This is even the case without having any event handlers in the code. When I use the code below and rest my finger on one of the buttons, the flickering behaviour will eventually occur.

```
import touchphat
import time

while True:
        print("test")
        time.sleep(0.1)
```

Am I doing something wrong or missing something? Is this a known issue and is there any workaround for this?

Edit:
The flickering increases with the amount of prints (f.e. when decreasing the time in the code above). I already had a look into the [cap1xxx](https://github.com/pimoroni/cap1xxx/blob/e33989debeb71f81e350ca75ab1918a99cfa6b84/library/cap1xxx.py) code, but I can't really see an issue there. As long as the button is still pressed, the state should not change and no new events should be generated...

**Comment by Gadgetoid** [comment]
I can't fathom what's going on here- how's your phat wired up, anything else connected?

Does something like the basic button example work sensibly for you?

**Comment by MegaAdragon** [comment]
> how's your phat wired up, anything else connected?

The phat is connected directly to a Raspberry Pi Zero. I used the pin header that came with the phat. There is nothing else connected to the GPIOs.

> Does something like the basic button example work sensibly for you?

Yes, the button example works without a problem. But as soon as I add a `print()` command somewhere else in the code, the issues starts to arise.

**Comment by Gadgetoid** [comment]
Sorry this fell by the wayside. Did you ever find a fix? This is so completely bizarre I don't even know where to begin.
