### ISSUE TITLE
Raspberry pi OS bullseye install errors

### ISSUE THREAD

**Issue by DocObvious** [pimoroni/touch-phat#9]
I tried to install the touchphat on a fresh install of raspberry pi OS bullseye and even the examples are throwing errors.

The errors are listed in this post:
https://forums.pimoroni.com/t/raspbian-os-bullseye-touchphat-errors/18497?u=mrobvious

Any help to rectify this would be great.

Thanks

**Comment by Gadgetoid** [comment]
You should just need to enable i2c. Either use the Raspberry Pi Configuration GUI or run this on the CLI: `sudo raspi-config nonint do_i2c 0`
